# Generated by Django 3.0.8 on 2020-08-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=10)),
                ('market', models.CharField(max_length=20)),
                ('crop', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
