# Generated by Django 3.0.8 on 2020-08-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_marketprices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketPrices',
        ),
    ]
