# Generated by Django 3.0.8 on 2020-08-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_marketprices'),
    ]

    operations = [
        migrations.CreateModel(
            name='WillPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('crop', models.CharField(max_length=20)),
                ('town', models.CharField(max_length=20)),
            ],
        ),
    ]
