# Generated by Django 3.1.2 on 2022-03-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_willplant_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_name', models.TextField()),
                ('tip_info', models.TextField()),
                ('tip_img', models.ImageField(upload_to='static/accounts/images')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FbModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('feedback', models.TextField()),
                ('phone', models.EmailField(max_length=254)),
                ('cr_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanSchemeForFarmers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('scheme_name', models.CharField(max_length=200)),
            ],
        ),
    ]
