# Generated by Django 4.0.4 on 2022-05-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploadimage',
            table='image_store',
        ),
    ]
