from django.contrib import admin
from django.urls import path,include
from . import views


urlpatterns = [
    path('', views.index,name='home'),
    path('basic/', views.home),
    #path('index/', views.userpage,name='userpage'),
    path('weather', views.weather,name='weather'),
    path('adminpanel', views.adminpanel,name='adminpanel'),
    # path('addcrop', views.addcrop,name='addcrop'),
    path('predictCrops', views.predictCrops,name='predict'),
    # path('addpest', views.addPest,name='addpest'),
    # path('predictpest', views.predictPest,name='predictpest'),
    path('signup',views.signup,name='signup'),
    path('login', views.handlelogin,name='handlelogin'),
    path('handlelogout', views.handlelogout, name='handlelogout'),
    path('Admin/', views.Admin,name='admin'),
    path('Farmer/', views.Farmer,name='farmer'),
    path('Weather/', views.showweather),
    path('Addschemes/', views.Addschemes),
    path('viewcrop', views.viewcrop,name='viewcrop'),
    path('AddShop', views.AddShop,name='AddShop'),
    path('Equipment',views.Equipment,name='Equipment'),
    path('shops', views.shops,name='shops'),
    path('userinfo', views.userinfo,name='userinfo') ,
    path('feedback',views.feedback,name='feedback'),
    path('soil/',views.soil,name='soil'),
    path('SoilLabs/',views.SoilLabs,name='SoilLabs'),
    path('WaterSheld/', views.WaterSheld,name='WaterSheld'),
    path('WaterSheldProgramm/', views.WaterSheldProgramm,name='WaterSheldProgramm'),
    path('Soilandaquaculturefieldtreatment/',views.Soilandaquaculturefieldtreatment,name='Soilandaquaculturefieldtreatment'),
    path('Soilandwaterconservationdraintreatment/',views.Soilandwaterconservationdraintreatment,name='Soilandwaterconservationdraintreatment'),
    path('pesticides/',views.pesticides,name='pesticides'),
    path('courses/',views.courses,name='courses'),
    path('admintips',views.admintips,name='admintips'),
    path('farmertip/',views.farmertip,name='farmertip'),
    path('user_resetpassword',views.user_resetpassword,name='user_resetpassword'),
    # path('predictwithoutprevious', views.predictwithoutprevious,name='predictwithoutprevious'),
    # path('marketforuser', views.marketforuser,name='marketforuser'),
    path('willplant', views.willplant,name='willplant'),
    path('userinfo', views.userinfo,name='userinfo') ,
    path('cropcountadminview', views.cropcountadminview,name='cropcountadminview'),
    path('govtschemes', views.govtschemes,name='govtschemes'),
    # path('adminmarketadd', views.adminmarketadd,name='adminmarketadd'),
    path('schemepmkisan', views.schemepmkisan,name='schemepmkisan'),
    # path('pestinformation', views.pestinformation,name='pestinformation'),
    # path('LeafSpotorSigatoka', views.LeafSpot,name='LeafSpot'),
    # path('PanamaWilt', views.PanamaWilt,name='Panama Wilt'),
    # path('AmricanBollWarm', views.AmricanBollWarm,name='AmricanBollWarm'),
    # path('PinkBollWarm', views.PinkBollWarm,name='PinkBollWarm'),
    # path('Leafhopper', views.Leafhopper,name='Leafhopper'),
    # path('Cornworm', views.Cornworm,name='Cornworm'),
    # path('PotatoLateBlightPhytophthorainfestans', views.PotatoLateBlightPhytophthorainfestans,name='PotatoLateBlightPhytophthorainfestans'),
    # path('Earlyshootborer', views.Earlyshootborer,name='Earlyshootborer')
]